# Generated by Django 6.0.4 on 2026-07-04 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type_item', models.CharField(choices=[('MEDICAMENT', 'Médicament'), ('EQUIPEMENT', 'Équipement'), ('CONSOMMABLE', 'Consommable')], max_length=50)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='structures.structure')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('structure', 'nom', 'type_item')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
