# Generated by Django 6.0.6 on 2026-07-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='structures.structure'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.stockitem'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('structure', 'nom', 'type_item')},
        ),
    ]
