# Generated by Django 6.0.6 on 2026-08-06 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
        ('structures', '0004_alter_structure_adresse_alter_structure_gestionnaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_reception', models.DateField(default=django.utils.timezone.localdate)),
                ('fournisseur', models.CharField(blank=True, default='', max_length=255)),
                ('reference_bon', models.CharField(blank=True, default='', max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvisionnements', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='structures.structure')),
            ],
            options={
                'verbose_name': 'Approvisionnement',
                'verbose_name_plural': 'Approvisionnements',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='approvisionnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='stock.approvisionnement'),
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('forme_pharmaceutique', models.CharField(choices=[('COMPRIME', 'Comprimé'), ('CAPSULE', 'Capsule'), ('GELULE', 'Gélule'), ('SIROP', 'Sirop'), ('SOLUTION_BUVABLE', 'Solution buvable'), ('INJECTABLE', 'Injectable'), ('CREME', 'Crème'), ('POMMADE', 'Pommade'), ('GEL', 'Gel'), ('SPRAY', 'Spray'), ('COLLYRE', 'Collyre'), ('SACHET', 'Sachet'), ('AMPOULE', 'Ampoule'), ('SUPPOSITOIRE', 'Suppositoire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tva', models.BooleanField(default=False)),
                ('en_reserve', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='structures.structure')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
                'unique_together': {('structure', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='LigneApprovisionnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forme_pharmaceutique', models.CharField(choices=[('COMPRIME', 'Comprimé'), ('CAPSULE', 'Capsule'), ('GELULE', 'Gélule'), ('SIROP', 'Sirop'), ('SOLUTION_BUVABLE', 'Solution buvable'), ('INJECTABLE', 'Injectable'), ('CREME', 'Crème'), ('POMMADE', 'Pommade'), ('GEL', 'Gel'), ('SPRAY', 'Spray'), ('COLLYRE', 'Collyre'), ('SACHET', 'Sachet'), ('AMPOULE', 'Ampoule'), ('SUPPOSITOIRE', 'Suppositoire'), ('AUTRE', 'Autre')], max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_peremption', models.DateField()),
                ('tva', models.BooleanField(default=False)),
                ('en_reserve', models.BooleanField(default=False)),
                ('approvisionnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.approvisionnement')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='stock.medicament')),
            ],
            options={
                'verbose_name': "Ligne d'approvisionnement",
                'verbose_name_plural': "Lignes d'approvisionnement",
                'ordering': ['id'],
            },
        ),
    ]
