# Generated by Django 6.0.6 on 2026-08-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_approvisionnement_stockmovement_approvisionnement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='quantite_reservee',
            field=models.PositiveIntegerField(default=0, help_text='Quantité réservée par des ventes en attente de paiement.'),
        ),
    ]
