# Generated by Django 6.0.6 on 2026-08-07 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockitem_quantite_reservee'),
        ('structures', '0004_alter_structure_adresse_alter_structure_gestionnaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='numero',
            field=models.CharField(blank=True, help_text="Numéro automatique de l'approvisionnement.", max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='approvisionnement',
            constraint=models.UniqueConstraint(condition=models.Q(('numero__isnull', False)), fields=('structure', 'numero'), name='unique_approvisionnement_structure_numero'),
        ),
    ]
