# Generated by Django 6.0.6 on 2026-08-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_approvisionnement_numero_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', '-created_at'], name='stock_stock_item_id_b3bc9c_idx'),
        ),
    ]
