# Generated by Django 6.0.6 on 2026-08-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockmovement_stock_stock_item_id_b3bc9c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='montant_total_declare',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total indique sur le bon de livraison.', max_digits=12),
        ),
        migrations.AddField(
            model_name='ligneapprovisionnement',
            name='stock_avant',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
