# Generated by Django 6.0.6 on 2026-08-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_approvisionnement_montant_total_declare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='nom_normalise',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Nom normalisé (sans accents, minuscules) utilisé par la recherche publique.', max_length=255),
        ),
    ]
