# Generated by Django 6.0.6 on 2026-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur'), ('PROPRIETAIRE', 'Proprietaire'), ('GESTIONNAIRE', 'Gestionnaire'), ('CAISSIER', 'Caissier'), ('PATIENT', 'Patient')], max_length=20),
        ),
    ]
