import {
  LayoutDashboard,
  Building2,
  FlaskConical,
  Monitor,
  HeartPulse,
  Package,
  Users,
  Clock,
  Bell,
  BarChart3,
  MessagesSquare,
  Settings,
} from "lucide-react";
import type { DashboardNavItem } from "../types";

export const hospitalNavigation: DashboardNavItem[] = [
  {
    label: "Dashboard",
    href: "/hospital",
    icon: LayoutDashboard,
    permission: "GESTIONNAIRE",
  },
  {
    label: "Profil",
    href: "/hospital/profile",
    icon: Building2,
    permission: "GESTIONNAIRE",
    module: "PROFIL",
    action: "CONSULTER",
    navItem: "profil",
  },
  {
    label: "Analyses",
    href: "/hospital/analyses",
    icon: FlaskConical,
    permission: "GESTIONNAIRE",
    navItem: "analyses",
  },
  {
    label: "Plateaux techniques",
    href: "/hospital/technical-platforms",
    icon: Monitor,
    permission: "GESTIONNAIRE",
    navItem: "plateaux-techniques",
  },
  {
    label: "Prises en charge",
    href: "/hospital/care-services",
    icon: HeartPulse,
    permission: "GESTIONNAIRE",
    navItem: "prises-en-charge",
  },
  {
    label: "Stock",
    href: "/hospital/stock",
    icon: Package,
    permission: "GESTIONNAIRE",
    module: "STOCK",
    action: "CONSULTER",
    navItem: "stock",
  },
  {
    label: "Mon equipe",
    href: "/hospital/employees",
    icon: Users,
    permission: "GESTIONNAIRE",
    navItem: "team",
  },
  {
    label: "Horaires",
    href: "/hospital/schedules",
    icon: Clock,
    permission: "GESTIONNAIRE",
    module: "HORAIRES",
    action: "CONSULTER",
    navItem: "horaires",
  },
  {
    label: "Notifications",
    href: "/hospital/notifications",
    icon: Bell,
    permission: "GESTIONNAIRE",
    module: "NOTIFICATIONS",
    action: "CONSULTER",
    navItem: "notifications",
  },
  {
    label: "Messagerie",
    href: "/hospital/chat",
    icon: MessagesSquare,
    permission: "GESTIONNAIRE",
    navItem: "messages",
  },
  {
    label: "Statistiques",
    href: "/hospital/statistics",
    icon: BarChart3,
    permission: "GESTIONNAIRE",
  },
  {
    label: "Paramètres",
    href: "/hospital/settings",
    icon: Settings,
    permission: "GESTIONNAIRE",
    module: "PARAMETRES",
    action: "CONSULTER",
  },
];
