import {
  Banknote,
  BarChart3,
  Bell,
  Building2,
  ClipboardList,
  History,
  LayoutDashboard,
  Settings,
  MessagesSquare,
  Package,
  Truck,
  ShoppingCart,
  CalendarClock,
  Pill,
  Clock,
  Receipt,
  Users,
  Stethoscope,
  Microscope,
  HeartPulse,
} from "lucide-react";
import type { DashboardNavItem } from "../types";

export const ownerNavigation: DashboardNavItem[] = [
  {
    label: "Dashboard",
    href: "/owner",
    icon: LayoutDashboard,
    permission: "PROPRIETAIRE",
  },
  {
    label: "Structures & Équipe",
    href: "/owner/team",
    icon: Users,
    permission: "PROPRIETAIRE",
  },
  
  // MODULES PHARMACIE
  {
    label: "Stock",
    href: "/owner/stock",
    icon: Package,
    permission: "PROPRIETAIRE",
    module: "STOCK",
    structureType: "PHARMACIE",
  },
  {
    label: "Médicaments",
    href: "/owner/medications",
    icon: Pill,
    permission: "PROPRIETAIRE",
    module: "STOCK",
    structureType: "PHARMACIE",
  },
  {
    label: "Vente",
    href: "/owner/sale",
    icon: ShoppingCart,
    permission: "PROPRIETAIRE",
    module: "VENTE",
    structureType: "PHARMACIE",
  },
  {
    label: "Caisse",
    href: "/owner/caisse",
    icon: Banknote,
    permission: "PROPRIETAIRE",
    module: "CAISSE",
    structureType: "PHARMACIE",
  },
  {
    label: "Factures",
    href: "/owner/factures",
    icon: Receipt,
    permission: "PROPRIETAIRE",
    module: "FACTURE",
    structureType: "PHARMACIE",
  },
  {
    label: "Approvisionnement",
    href: "/owner/supply",
    icon: Truck,
    permission: "PROPRIETAIRE",
    module: "APPROVISIONNEMENT",
    structureType: "PHARMACIE",
  },
  {
    label: "Inventaire",
    href: "/owner/inventaires",
    icon: ClipboardList,
    permission: "PROPRIETAIRE",
    module: "INVENTAIRE",
    structureType: "PHARMACIE",
  },
  {
    label: "Péremption",
    href: "/owner/peremption",
    icon: CalendarClock,
    permission: "PROPRIETAIRE",
    module: "PEREMPTION",
    structureType: "PHARMACIE",
  },
  {
    label: "Historique",
    href: "/owner/history",
    icon: History,
    permission: "PROPRIETAIRE",
    module: "HISTORIQUE",
    structureType: "PHARMACIE",
  },
  {
    label: "Alertes",
    href: "/owner/alertes",
    icon: Bell,
    permission: "PROPRIETAIRE",
    module: "ALERTES",
    structureType: "PHARMACIE",
  },
  {
    label: "Statistiques",
    href: "/owner/statistics",
    icon: BarChart3,
    permission: "PROPRIETAIRE",
    module: "STATISTIQUES",
    structureType: "PHARMACIE",
  },
  {
    label: "Horaires",
    href: "/owner/schedules",
    icon: Clock,
    permission: "PROPRIETAIRE",
    module: "HORAIRES",
    structureType: "PHARMACIE",
  },
  {
    label: "Notifications",
    href: "/owner/notifications",
    icon: Bell,
    permission: "PROPRIETAIRE",
    module: "NOTIFICATIONS",
    structureType: "PHARMACIE",
  },
  
  // MODULES HOPITAL
  {
    label: "Services Médicaux",
    href: "/owner/services-medicaux",
    icon: Stethoscope,
    permission: "PROPRIETAIRE",
    module: "SERVICES_MEDICAUX",
    structureType: "HOPITAL",
  },
  {
    label: "Plateaux Techniques",
    href: "/owner/plateaux-techniques",
    icon: Microscope,
    permission: "PROPRIETAIRE",
    module: "PLATEAUX_TECHNIQUES",
    structureType: "HOPITAL",
  },
  {
    label: "Prises en Charge",
    href: "/owner/prises-en-charge",
    icon: HeartPulse,
    permission: "PROPRIETAIRE",
    module: "PRISES_EN_CHARGE",
    structureType: "HOPITAL",
  },
  
  // MODULE EXCLUSIF PROPRIETAIRE (tous types)
  {
    label: "Messagerie",
    href: "/owner/chat",
    icon: MessagesSquare,
    permission: "PROPRIETAIRE",
  },
  
  // MODULES TOUJOURS ACCESSIBLES (tous types)
  {
    label: "Profil",
    href: "/owner/profile",
    icon: Building2,
    permission: "PROPRIETAIRE",
    navItem: "profil",
  },
  {
    label: "Paramètres",
    href: "/owner/settings",
    icon: Settings,
    permission: "PROPRIETAIRE",
  },
];
