import {
  LayoutDashboard,
  Building2,
  Package,
  Truck,
  Clock,
  Bell,
  Settings,
  ShoppingCart,
  ClipboardList,
  History,
  CalendarClock,
  Pill,
} from "lucide-react";
import type { DashboardNavItem } from "../types";

export const pharmacyNavigation: DashboardNavItem[] = [
  {
    label: "Dashboard",
    href: "/pharmacy",
    icon: LayoutDashboard,
  },
  {
    label: "Profil",
    href: "/pharmacy/profile",
    icon: Building2,
    module: "PROFIL",
    action: "CONSULTER",
    navItem: "profil",
  },
  {
    label: "Stock",
    href: "/pharmacy/stock",
    icon: Package,
    module: "STOCK",
    action: "CONSULTER",
    navItem: "stock",
  },
  {
    label: "Medicaments",
    href: "/pharmacy/medications",
    icon: Pill,
    module: "STOCK",
    action: "CONSULTER",
    navItem: "stock",
  },
  {
    label: "Vente",
    href: "/pharmacy/sale",
    icon: ShoppingCart,
    module: "VENTE",
    action: "CONSULTER",
    navItem: "vente",
  },
  {
    label: "Approvisionnement",
    href: "/pharmacy/supply",
    icon: Truck,
    module: "APPROVISIONNEMENT",
    action: "CONSULTER",
    navItem: "stock",
  },
  {
    label: "Inventaire",
    href: "/pharmacy/inventory",
    icon: ClipboardList,
    module: "INVENTAIRE",
    action: "CONSULTER",
  },
  {
    label: "Peremption",
    href: "/pharmacy/peremption",
    icon: CalendarClock,
    module: "PEREMPTION",
    action: "CONSULTER",
    navItem: "stock",
  },
  {
    label: "Historique",
    href: "/pharmacy/history",
    icon: History,
    module: "HISTORIQUE",
    action: "CONSULTER",
  },
  {
    label: "Alertes",
    href: "/pharmacy/alertes",
    icon: Bell,
    module: "ALERTES",
    action: "CONSULTER",
  },
  {
    label: "Horaires",
    href: "/pharmacy/schedules",
    icon: Clock,
    module: "HORAIRES",
    action: "CONSULTER",
    navItem: "horaires",
  },
  {
    label: "Notifications",
    href: "/pharmacy/notifications",
    icon: Bell,
    module: "NOTIFICATIONS",
    action: "CONSULTER",
    navItem: "notifications",
  },
  {
    label: "Parametres",
    href: "/pharmacy/settings",
    icon: Settings,
    module: "PARAMETRES",
    action: "CONSULTER",
  },
];
