# Generated by Django 6.0.6 on 2026-06-30 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structures.structure'),
        ),
    ]
