# Generated by Django 6.0.6 on 2026-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='nav_item',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Identifiant de l'élément de navigation concerné (ex: structures, profil, messages, notifications)", max_length=50),
        ),
    ]
