# Generated by Django 6.0.6 on 2026-08-08 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_nav_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
