# Generated by Django 6.0.6 on 2026-08-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_pushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificatio_utilisa_371a0c_idx',
            old_name='notif_push_user_active_idx',
        ),
    ]
