# Generated by Django 6.0.6 on 2026-07-24 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('user_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
