# Generated by Django 6.0.6 on 2026-07-31 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.CharField(db_index=True, max_length=255)),
                ('intent_type', models.CharField(choices=[('SYMPTOM_SEARCH', 'Recherche symptôme'), ('MEDICATION_SEARCH', 'Recherche médicament'), ('LOCATION_SEARCH', 'Recherche lieu'), ('AVAILABILITY_SEARCH', 'Recherche disponibilité'), ('EMERGENCY', 'Urgence')], max_length=50)),
                ('target_search_type', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-priority', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(db_index=True)),
                ('content_original', models.TextField()),
                ('search_type', models.CharField(choices=[('MEDICAMENT', 'Médicament'), ('MALADIE', 'Maladie'), ('ANALYSE', 'Analyse'), ('EXAMEN', 'Examen'), ('SERVICE_MEDICAL', 'Service médical'), ('EQUIPEMENT', 'Équipement'), ('PLATEAU_TECHNIQUE', 'Plateau technique')], db_index=True, max_length=50)),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.UUIDField()),
                ('structure_id', models.UUIDField(db_index=True)),
                ('structure_nom', models.CharField(max_length=255)),
                ('structure_type', models.CharField(max_length=20)),
                ('structure_adresse', models.CharField(max_length=255)),
                ('structure_telephone', models.CharField(max_length=30)),
                ('structure_latitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('structure_longitude', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('structure_statut', models.CharField(default='ACTIVE', max_length=20)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(db_index=True, max_length=255, unique=True)),
                ('synonyms', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.AddField(
            model_name='searchlog',
            name='search_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='user_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='user_lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user', '-created_at'], name='search_sear_user_id_aa7ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query', '-created_at'], name='search_sear_query_58a6b2_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['search_type', 'is_available'], name='search_sear_search__23a48d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['structure_id', 'is_available'], name='search_sear_structu_ef9a01_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['content_type', 'object_id'], name='search_sear_content_85ca57_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['structure_latitude', 'structure_longitude'], name='search_sear_structu_abd6de_idx'),
        ),
    ]
