# Generated by Django 6.0.6 on 2026-08-06 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0004_stockitem_quantite_reservee'),
        ('structures', '0004_alter_structure_adresse_alter_structure_gestionnaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nb_articles', models.PositiveIntegerField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ImpressionFacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imprime_le', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ventes.facture')),
                ('imprime_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impressions_factures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impression de facture',
                'verbose_name_plural': 'Impressions de factures',
                'ordering': ['-imprime_le'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile money'), ('VIREMENT', 'Virement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effectue_le', models.DateTimeField(auto_now_add=True)),
                ('encaisse_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-effectue_le'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='paiement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='ventes.paiement'),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30)),
                ('etat', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée')], db_index=True, default='EN_PREPARATION', max_length=25)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('transmise_le', models.DateTimeField(blank=True, null=True)),
                ('validee_le', models.DateTimeField(blank=True, null=True)),
                ('annulee_le', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, help_text='Délai de paiement : au-delà, la vente expire automatiquement.', null=True)),
                ('motif_annulation', models.CharField(blank=True, default='', max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nb_articles', models.PositiveIntegerField(default=0)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_annulees', to=settings.AUTH_USER_MODEL)),
                ('prepare_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_preparees', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='structures.structure')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='vente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='ventes.vente'),
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('forme_pharmaceutique', models.CharField(max_length=50)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='stock.medicament')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='ventes.vente'),
        ),
        migrations.AddConstraint(
            model_name='vente',
            constraint=models.UniqueConstraint(fields=('structure', 'numero'), name='unique_vente_structure_numero'),
        ),
    ]
