# Generated by Django 6.0.6 on 2026-08-06 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockitem_quantite_reservee'),
        ('structures', '0004_alter_structure_adresse_alter_structure_gestionnaire_and_more'),
        ('ventes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='tva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vente',
            name='nom_client',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vente',
            name='telephone_client',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE_MONEY', 'Mobile money'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='etat',
            field=models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('EN_COURS', 'En cours'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée')], db_index=True, default='EN_PREPARATION', max_length=25),
        ),
        migrations.CreateModel(
            name='OperationCaisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('CREATION', 'Création de la vente'), ('TRANSMISSION', 'Transmission à la caisse'), ('OUVERTURE', 'Ouverture par le caissier'), ('VALIDATION', 'Validation du paiement'), ('ANNULATION', 'Annulation'), ('IMPRESSION', 'Impression du reçu'), ('REIMPRESSION', 'Réimpression du reçu'), ('RETOUR_CAISSE', 'Retour en caisse')], max_length=20)),
                ('resultat', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], default='SUCCES', max_length=10)),
                ('detail', models.TextField(blank=True, default='')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_caisse', to='structures.structure')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_caisse', to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Opération caisse',
                'verbose_name_plural': 'Opérations caisse',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='RetourCaisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30)),
                ('motif', models.CharField(choices=[('CLIENT_SANS_ARGENT', 'Client sans argent'), ('PRODUIT_RETIRE', 'Produit retiré'), ('ERREUR_QUANTITE', 'Erreur de quantité'), ('ERREUR_PRIX', 'Erreur de prix'), ('RETOUR_ACCEPTE', 'Retour accepté'), ('PRODUIT_DEFECTUEUX', 'Produit défectueux'), ('AUTRE', 'Autre')], max_length=30)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('effectue_le', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nb_articles', models.PositiveIntegerField(default=0)),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_caisse', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retours_caisse', to='structures.structure')),
                ('vente', models.ForeignKey(help_text="Vente (et facture) d'origine du retour.", on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Retour en caisse',
                'verbose_name_plural': 'Retours en caisse',
                'ordering': ['-effectue_le'],
            },
        ),
        migrations.CreateModel(
            name='RetourCaisseLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour', to='stock.medicament')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.retourcaisse')),
            ],
            options={
                'verbose_name': 'Ligne de retour en caisse',
                'verbose_name_plural': 'Lignes de retour en caisse',
                'ordering': ['id'],
            },
        ),
    ]
