# Generated by Django 6.0.6 on 2026-08-08 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0005_equipestructure_structures__utilisa_cb6ddd_idx'),
        ('ventes', '0002_lignevente_tva_vente_nom_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationcaisse',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='retourcaisse',
            name='effectue_le',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='validee_le',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['etat', 'date_expiration'], name='ventes_vent_etat_8923e6_idx'),
        ),
    ]
