# Generated by Django 6.0.6 on 2026-08-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_facture_structure_beneficiaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationcaisse',
            name='action',
            field=models.CharField(choices=[('CREATION', 'Création de la vente'), ('TRANSMISSION', 'Transmission à la caisse'), ('OUVERTURE', 'Ouverture par le caissier'), ('VALIDATION', 'Validation du paiement'), ('ANNULATION', 'Annulation'), ('IMPRESSION', 'Impression du reçu'), ('REIMPRESSION', 'Réimpression du reçu'), ('RETOUR_CAISSE', 'Retour en caisse'), ('GENERATION_FACTURE', 'Génération de la facture')], max_length=20),
        ),
    ]
