# Generated by Django 6.0.6 on 2026-07-24 14:25

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('type', models.CharField(choices=[('MALADIE', 'Maladie'), ('ANALYSE', 'Analyse'), ('EXAMEN', 'Examen'), ('SERVICE_MEDICAL', 'Service médical')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalogue',
                'verbose_name_plural': 'Catalogues',
                'ordering': ['type', 'nom'],
                'indexes': [models.Index(fields=['type', 'nom'], name='catalogues__type_5408f6_idx'), models.Index(fields=['est_actif'], name='catalogues__est_act_e51427_idx')],
                'constraints': [models.UniqueConstraint(fields=('nom', 'type'), name='unique_nom_type_catalogue')],
            },
        ),
    ]
