# Generated by Django 6.0.6 on 2026-08-07 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0004_alter_structure_adresse_alter_structure_gestionnaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('OPERATIONNELLE', 'Opérationnelle'), ('SUPERVISION', 'Supervision')], db_index=True, max_length=20)),
                ('type', models.CharField(choices=[('STOCK_FAIBLE', 'Stock faible'), ('RUPTURE_STOCK', 'Rupture de stock'), ('RETOURS_CAISSE_ANORMAUX', 'Retours caisse inhabituels'), ('VENTES_ANNULEES_ANORMALES', 'Annulations de vente inhabituelles')], db_index=True, max_length=40)),
                ('priorite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('MOYENNE', 'Moyenne'), ('INFORMATION', 'Information')], db_index=True, max_length=15)),
                ('module', models.CharField(choices=[('APPROVISIONNEMENT', 'Approvisionnement'), ('STOCK', 'Stock'), ('VENTE', 'Vente'), ('CAISSE', 'Caisse'), ('INVENTAIRE', 'Inventaire')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('donnees', models.JSONField(blank=True, default=dict, help_text="Données contextuelles propres au type d'alerte.")),
                ('est_resolue', models.BooleanField(db_index=True, default=False, help_text='True lorsque le système détecte que la situation est revenue à la normale (résolution automatique).')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('texte_recherche', models.CharField(blank=True, default='', help_text='Index de recherche en minuscules (titre, type, catégorie, module, médicament, utilisateur concerné).', max_length=2000)),
                ('lu_par', models.ManyToManyField(blank=True, help_text="Utilisateurs ayant marqué cette alerte comme lue. L'état de lecture est propre à chaque utilisateur.", related_name='alertes_lues', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='structures.structure')),
                ('utilisateur_concerne', models.ForeignKey(blank=True, help_text="Utilisateur directement impliqué dans la situation détectée (ex. caissier à l'origine des retours caisse).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertes_concernees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['structure', 'est_resolue'], name='alertes_ale_structu_b00554_idx')],
            },
        ),
    ]
