# Generated by Django 6.0.6 on 2026-08-06 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0004_stockitem_quantite_reservee'),
        ('structures', '0004_alter_structure_adresse_alter_structure_gestionnaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30)),
                ('role_createur', models.CharField(blank=True, default='', help_text="Role de l'utilisateur au moment de la generation (snapshot).", max_length=30)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='structures.structure')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='InventaireLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('forme_pharmaceutique', models.CharField(blank=True, default='', max_length=50)),
                ('quantite_physique', models.PositiveIntegerField(default=0)),
                ('quantite_reservee', models.PositiveIntegerField(default=0)),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('STOCK_FAIBLE', 'Stock faible'), ('RUPTURE', 'Rupture')], max_length=20)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventaires.inventaire')),
                ('medicament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='stock.medicament')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'ordering': ['nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventaire',
            constraint=models.UniqueConstraint(fields=('structure', 'numero'), name='unique_inventaire_structure_numero'),
        ),
    ]
