# Generated by Django 6.0.4 on 2026-07-04 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        ('structures', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMedical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_medicaux', to='catalogues.catalogue')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_medicaux', to='structures.structure')),
            ],
            options={
                'unique_together': {('structure', 'catalogue')},
            },
        ),
    ]
