# Generated by Django 6.0.6 on 2026-07-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_medical', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemedical',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_medicaux', to='structures.structure'),
        ),
        migrations.AlterUniqueTogether(
            name='servicemedical',
            unique_together={('structure', 'catalogue')},
        ),
    ]
