# Generated by Django 6.0.6 on 2026-07-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_medical', '0002_initial'),
        ('structures', '0003_structureservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemedical',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_medicaux', to='structures.structureservice'),
        ),
        migrations.AlterUniqueTogether(
            name='servicemedical',
            unique_together={('structure', 'service')},
        ),
        migrations.RemoveField(
            model_name='servicemedical',
            name='catalogue',
        ),
    ]
