# Generated by Django 6.0.4 on 2026-07-04 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseEnCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.CharField(blank=True, choices=[('COMPLET', 'Complet'), ('PARTIEL', 'Partiel'), ('ORIENTATION', 'Orientation')], max_length=20, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='catalogues.catalogue')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='structures.structure')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('structure', 'catalogue'), name='unique_structure_catalogue')],
            },
        ),
    ]
