# Generated by Django 6.0.6 on 2026-06-30 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriseEnCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='prise_en_charge.maladie')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='structures.structure')),
            ],
            options={
                'unique_together': {('structure', 'maladie')},
            },
        ),
    ]
