# Generated by Django 6.0.6 on 2026-07-24 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prise_en_charge', '0001_initial'),
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priseencharge',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='structures.structure'),
        ),
        migrations.AddConstraint(
            model_name='priseencharge',
            constraint=models.UniqueConstraint(fields=('structure', 'catalogue'), name='unique_structure_catalogue'),
        ),
    ]
