# Generated by Django 6.0.6 on 2026-07-29 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prise_en_charge', '0002_initial'),
        ('structures', '0003_structureservice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='priseencharge',
            name='unique_structure_catalogue',
        ),
        migrations.AddField(
            model_name='priseencharge',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='structures.structureservice'),
        ),
        migrations.AddConstraint(
            model_name='priseencharge',
            constraint=models.UniqueConstraint(fields=('structure', 'service'), name='unique_structure_service_pec'),
        ),
        migrations.RemoveField(
            model_name='priseencharge',
            name='catalogue',
        ),
    ]
