# Generated by Django 6.0.6 on 2026-07-24 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=10)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('est_ferme', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['jour'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('HOPITAL', 'Hôpital'), ('PHARMACIE', 'Pharmacie')], db_index=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='structures/photos/')),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(db_index=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIVE', 'Active'), ('REFUSEE', 'Refusée')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True, default='')),
                ('est_supprimee', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
