# Generated by Django 6.0.6 on 2026-06-30 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('HOPITAL', 'Hôpital'), ('PHARMACIE', 'Pharmacie')], db_index=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='structures/photos/')),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(db_index=True, max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIVE', 'Active'), ('REFUSEE', 'Refusée')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
