# Generated by Django 6.0.6 on 2026-07-10 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='structures.structure')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_ajout'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'structure'), name='unique_favori_utilisateur_structure')],
            },
        ),
    ]
