# Generated by Django 6.0.6 on 2026-07-24 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favori',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='structure',
            name='gestionnaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='structure',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horaire',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='structures.structure'),
        ),
        migrations.AddField(
            model_name='favori',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='structures.structure'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['latitude', 'longitude'], name='structures__latitud_0f5514_idx'),
        ),
        migrations.AddConstraint(
            model_name='horaire',
            constraint=models.UniqueConstraint(fields=('structure', 'jour'), name='unique_horaire_structure_jour'),
        ),
        migrations.AddConstraint(
            model_name='favori',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'structure'), name='unique_favori_utilisateur_structure'),
        ),
    ]
