# Generated by Django 6.0.6 on 2026-06-30 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='gestionnaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to=settings.AUTH_USER_MODEL),
        ),
    ]
