# Generated by Django 6.0.6 on 2026-07-29 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('MALADIE', 'Maladie'), ('ANALYSE', 'Analyse'), ('EXAMEN', 'Examen'), ('SERVICE_MEDICAL', 'Service médical')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('est_actif', models.BooleanField(db_index=True, default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['type', 'nom'],
                'indexes': [models.Index(fields=['type', 'nom'], name='structures__type_ddbf55_idx'), models.Index(fields=['est_actif'], name='structures__est_act_04ba94_idx')],
                'constraints': [models.UniqueConstraint(fields=('nom', 'type'), name='unique_nom_type_service')],
            },
        ),
    ]
