# Generated by Django 6.0.6 on 2026-07-10 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_favori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=10)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('est_ferme', models.BooleanField(default=False)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='structures.structure')),
            ],
            options={
                'ordering': ['jour'],
                'constraints': [models.UniqueConstraint(fields=('structure', 'jour'), name='unique_horaire_structure_jour')],
            },
        ),
    ]
