# Generated by Django 6.0.6 on 2026-08-05 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0003_structureservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='structure',
            name='gestionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structure',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='EquipeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PROPRIETAIRE', 'Proprietaire'), ('GESTIONNAIRE', 'Gestionnaire'), ('CAISSIER', 'Caissier')], db_index=True, max_length=20)),
                ('statut', models.CharField(choices=[('INVITE', 'Invite'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu')], db_index=True, default='INVITE', max_length=20)),
                ('date_invitation', models.DateTimeField(auto_now_add=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='structures.structure')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures_membres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de structure',
                'verbose_name_plural': 'Equipe des structures',
                'ordering': ['structure__nom', 'role', 'utilisateur__nom'],
                'indexes': [models.Index(fields=['structure', 'role'], name='structures__structu_3d8a3c_idx'), models.Index(fields=['utilisateur', 'statut'], name='structures__utilisa_8d8a49_idx')],
                'constraints': [models.UniqueConstraint(fields=('structure', 'utilisateur'), name='unique_equipe_structure_utilisateur')],
            },
        ),
    ]
