# Generated by Django 6.0.6 on 2026-08-08 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0004_alter_structure_adresse_alter_structure_gestionnaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipestructure',
            index=models.Index(fields=['utilisateur', 'role', 'statut'], name='structures__utilisa_cb6ddd_idx'),
        ),
    ]
