# Generated by Django 6.0.6 on 2026-08-13 14:55

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0005_equipestructure_structures__utilisa_cb6ddd_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembrePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=40)),
                ("action", models.CharField(db_index=True, max_length=40)),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="structures.equipestructure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission membre",
                "verbose_name_plural": "Permissions membres",
            },
        ),
        migrations.AddConstraint(
            model_name="membrepermission",
            constraint=models.UniqueConstraint(
                fields=("equipe", "module", "action"),
                name="unique_membre_module_action",
            ),
        ),
        migrations.AddIndex(
            model_name="membrepermission",
            index=models.Index(fields=["equipe", "module"], name="membre_equipe_module_idx"),
        ),
    ]
