# Generated by Django 6.0.6 on 2026-08-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0006_membrepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horaire',
            options={'ordering': ['jour', 'position', 'heure_ouverture']},
        ),
        migrations.RemoveConstraint(
            model_name='horaire',
            name='unique_horaire_structure_jour',
        ),
        migrations.RenameIndex(
            model_name='membrepermission',
            new_name='structures__equipe__458234_idx',
            old_name='membre_equipe_module_idx',
        ),
        migrations.AddField(
            model_name='horaire',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ordre de la période au sein de la journée (plusieurs périodes/jour).'),
        ),
        migrations.AddIndex(
            model_name='horaire',
            index=models.Index(fields=['structure', 'jour'], name='structures__structu_2e4c14_idx'),
        ),
    ]
