# Generated by Django 6.0.6 on 2026-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0007_alter_horaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipestructure',
            name='role',
            field=models.CharField(blank=True, db_index=True, help_text='Rôle personnalisé défini par le propriétaire (texte libre optionnel)', max_length=100, null=True),
        ),
    ]
