# Generated by Django 6.0.6 on 2026-08-07 09:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0004_alter_structure_adresse_alter_structure_gestionnaire_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('APPROVISIONNEMENT_CREE', 'Approvisionnement enregistré'), ('INVENTAIRE_GENERE', 'Inventaire généré'), ('CAISSE_RETOUR', 'Retour caisse')], max_length=40)),
                ('role', models.CharField(blank=True, default='', help_text="Rôle de l'utilisateur au moment de l'action (trace).", max_length=30)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('donnees', models.JSONField(blank=True, default=dict, help_text="Données contextuelles propres au type d'événement.")),
                ('texte_recherche', models.CharField(blank=True, default='', help_text='Index de recherche en minuscules (type, utilisateur, numéros, produits).', max_length=2000)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_historique', to='structures.structure')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements_historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Événement d'historique",
                'verbose_name_plural': "Événements d'historique",
                'ordering': ['-cree_le'],
            },
        ),
    ]
