# Generated by Django 6.0.6 on 2026-08-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementhistorique',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='evenementhistorique',
            name='type',
            field=models.CharField(choices=[('APPROVISIONNEMENT_CREE', 'Approvisionnement enregistré'), ('INVENTAIRE_GENERE', 'Inventaire généré'), ('CAISSE_RETOUR', 'Retour caisse')], db_index=True, max_length=40),
        ),
    ]
