# Generated by Django 6.0.6 on 2026-08-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0002_alter_evenementhistorique_cree_le_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementhistorique',
            name='type',
            field=models.CharField(choices=[('APPROVISIONNEMENT_CREE', 'Approvisionnement enregistré'), ('STOCK_SUPPRIME', 'Stock supprimé'), ('INVENTAIRE_GENERE', 'Inventaire généré'), ('CAISSE_RETOUR', 'Retour caisse')], db_index=True, max_length=40),
        ),
    ]
