# Generated by Django 6.0.4 on 2026-07-04 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avisstructure',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaireavis',
            name='avis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='avis.avisstructure'),
        ),
        migrations.AddConstraint(
            model_name='avisstructure',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'structure'), name='unique_avis_utilisateur_structure'),
        ),
    ]
