# Generated by Django 6.0.4 on 2026-07-04 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('STRUCTURE', 'Structure'), ('PLATEFORME', 'Plateforme')], max_length=20)),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='structures.structure')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
