# Generated by Django 6.0.6 on 2026-07-27 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('STRUCTURE', 'Structure'), ('PLATEFORME', 'Plateforme')], max_length=20)),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('sujet', models.CharField(blank=True, default='', max_length=255)),
                ('categorie', models.CharField(choices=[('BUG', 'Bug'), ('SUGGESTION', 'Suggestion'), ('SIGNALEMENT', 'Signalement'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('statut', models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('TRAITE', 'Traité')], default='NON_LU', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='structures.structure')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
