# Generated by Django 6.0.6 on 2026-08-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='statut',
            field=models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('TRAITE', 'Traité')], db_index=True, default='NON_LU', max_length=20),
        ),
    ]
